#Testing Container File 
FROM ubi8/ubi:8.5
MAINTAINER Rajanikant Yadav<rajanikanty@gmail.com>
LABEL description="This is apache container"
RUN yum install -y httpd && \
    yum clean all
RUN echo "This is Apache container file" > /var/www/html/index.html

EXPOSE 80

CMD ["httpd", "-D" ,"FOREGROUND"]
